config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'dashboard#index'

  # <-- Auth
  get '/login', to: 'auth#login', as: 'login'
  post '/login', to: 'api/auth#login'
  post '/logout', to: 'api/auth#logout', as: 'logout'
  get '/registration', to: 'auth#registration', as: 'registration'
  post '/registration', to: 'api/auth#registration'
  get '/forgot-password', to: 'auth#forgot_password', as: 'forgot_password'
  post '/forgot-password', to: 'api/auth#forgot_password'
  # -->

  resources :messages, only: %i[index show]
  resources :tasks, only: %i[index show]
  resources :groups, only: %i[index show]
  resources :users, only: %i[index show] do
    collection do
      get 'me', to: 'users#me', as: 'me'
      delete '', to: 'users#delete_selected', as: 'delete_selected'
    end
  end
  resources :reports, only: %i[index show]
  resources :settings, only: %i[index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_message.rb
# frozen_string_literal: true

class ChatMessage < ApplicationRecord
end

app/models/chat_room.rb
# frozen_string_literal: true

class ChatRoom < ApplicationRecord
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
end

app/models/password.rb
# frozen_string_literal: true

class Password < ApplicationRecord
  acts_as_paranoid
  has_secure_password

  belongs_to :user
end

app/models/refresh_token.rb
# frozen_string_literal: true

class RefreshToken < ApplicationRecord
  belongs_to :user
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  acts_as_paranoid

  has_many :refresh_tokens, dependent: :destroy
  has_one :password, dependent: :destroy
  has_one :user_secret, dependent: :destroy

  validates :email, uniqueness: true

  enum role: Constants::USER_ROLES

  def full_name
    f_name = first_name || ''
    l_name = last_name || ''
    "#{f_name} #{l_name}"
  end
end

app/models/user_online_status.rb
# frozen_string_literal: true

class UserOnlineStatus < ApplicationRecord
  belongs_to :user
end

app/models/user_secret.rb
# frozen_string_literal: true

class UserSecret < ApplicationRecord
  belongs_to :user
end

app/controllers/auth_controller.rb
# frozen_string_literal: true

class AuthController < ApplicationController
  def login; end

  def registration; end

  def forgot_password; end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

class GroupsController < ApplicationController
  def index; end

  def show; end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show; end

  def me; end

  def delete_selected
    ids = params[:id].split(',')
    users = User.where(id: ids)

    return if ids.blank?

    users.each(&:destroy!)
    render js: "window.location = '/users'"
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_path?(path = '')
    controller.controller_name == path.downcase
  end

  def full_title(page_title = '')
    base_title = 'RTemp'
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      "#{controller.controller_name.capitalize} | #{base_title}"
    end
  end

  def set_header?(state = false)
    !state
  end

  def log_in?
    @current_user.present?
  end

  def path_name(page_header_title = '')
    if page_header_title.present?
      page_header_title
    else
      controller.controller_name.capitalize
    end
  end

  def online_status_to_color(status)
    case status
    when 'online'
      'text-green'
    when 'offline'
      'text-red'
    else
      'text-gray'
    end
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/reports_helper.rb
# frozen_string_literal: true

module ReportsHelper
end

app/helpers/settings_helper.rb
# frozen_string_literal: true

module SettingsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_dropdown.html.erb
<div
  data-users-dropdown-target="userActions"
  aria-orientation="vertical"
  aria-labelledby="menu-button"
  class="z-40 hidden absolute top-[50px] left-[50px] w-[160px] rounded-[3px] border-[1px] border-sidebar bg-white divide-[2px] focus:outline-none text-black"
>
  <div class="py-1" role="none">
    <%# <div data-action="click->checkbox-select-all#getCheckedUserIds" role="menuitem" tabindex="-1" id="menu-item-0" class="block px-3 py-2 hover:bg-sidebar hover:text-white">
      Message group
    </div> %>
    <div data-action="click->checkbox-select-all#deleteUsers" role="menuitem" tabindex="-1" id="menu-item-1" class="block px-3 py-2 hover:bg-sidebar text-red">
      Delete
    </div>
  </div>
</div>

app/views/users/_user_list_table.html.erb
<table class="user-table w-full text-dark-blue border-spacing-y-[8px] border-separate">
  <thead class="uppercase text-[12px]">
    <tr>
      <th scope="col" class="p-3">
        <div class="flex">
          <input type="checkbox" id="checkbox-select-all" class="rounded border-gray" data-checkbox-select-all-target="checkboxAll">
        </div>
      </th>
      <th scope="col" class="p-3"></th>
      <th scope="col" class="p-3">
        <div class="flex items-center">
          Name
        </div>
      </th>
      <th scope="col" class="p-3">
        <div class="flex items-center">
          Role
        </div>
      </th>
      <th scope="col" class="p-3">
        <div class="flex items-center">
          Country
        </div>
      </th>
      <th scope="col" class="p-3">
        <div class="flex items-center">
          Last online
        </div>
      </th>
      <th scope="col" class="p-3">
        <div class="flex items-center">
          Message
        </div>
      </th>
    </tr>
  </thead>
  <tbody class="text-[16px]">
    <% @users.each do |u| %>
      <tr class="bg-white border border-black <%= @current_user != u ? 'hover:cursor-pointer hover' : '' %>" data-action="<%= @current_user != u ? 'click->checkbox-select-all#selectCheckbox' : '' %>">
        <td scope="col" class="p-3 w-[120px]">
          <% if (@current_user != u) %>
            <label class="flex w-fit">
              <input id="checkbox" type="checkbox" class="rounded border-gray" data-checkbox-select-all-target="checkbox" value="<%= u.id %>">
            </label>
          <% end %>
        </td>
        <td scope="col" class="p-3 w-[120px]">
          <%= image_tag('avatar-thumbnail.png', class: 'w-[35px]') %>
        </td>
        <td scope="col" class="p-3">
          <%= @current_user.full_name %>
        </td>
        <td scope="col" class="uppercase p-3 w-[200px]">
          <%= u.role %>
        </td>
        <td scope="col" class="p-3 w-[240px]">
          <%= u.country %>
        </td>
        <td scope="col" class="p-3 w-[320px]">
          <p class="<%= online_status_to_color(u.role) %>">
            <%= u.role %>
          </p>
        </td>
        <td id="action" scope="col" class="uppercase p-3 w-[80px]">
          <% if (@current_user != u) %>
            <%= link_to(image_tag('user-message-button.svg', class: 'w-[40px]', data: { disableCheck: true }), message_path(u), data: { disableCheck: true }) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<div class="flex flex-col" data-controller="checkbox-select-all">
  <div data-controller="users-dropdown">
    <div data-action="click->users-dropdown#toggleUserActions" data-type="menu" data-users-dropdown-target="usersMenu" class="px-[16px] py-[8px] flex cursor-pointer relative w-fit rounded-[4px] text-white bg-blue select-none">
      <p class="pointer-events-none">Actions</p>
      <%= render 'dropdown' %>
    </div>
  </div>
  <%= render 'user_list_table' %>
</div>

app/views/users/me.html.erb
<% provide(:page_title, @current_user.full_name) %>
<% provide(:page_header_title, 'Profile') %>

<div>

</div>