config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'dashboard#index'

  # <-- Auth
  get '/login', to: 'auth#login', as: 'login'
  post '/login', to: 'api/auth#login'
  post '/logout', to: 'api/auth#logout', as: 'logout'
  get '/registration', to: 'auth#registration', as: 'registration'
  post '/registration', to: 'api/auth#registration'
  get '/forgot-password', to: 'auth#forgot_password', as: 'forgot_password'
  post '/forgot-password', to: 'api/auth#forgot_password'
  # -->

  resources :messages, only: %i[index show]
  resources :tasks, only: %i[index show]
  resources :groups, only: %i[index show]
  resources :users, only: %i[index show] do
    collection do
      get 'me', to: 'users#me', as: 'me'
      delete '', to: 'users#delete_selected', as: 'delete_selected'
    end
  end
  resources :reports, only: %i[index show]
  resources :settings, only: %i[index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_message.rb
# frozen_string_literal: true

class ChatMessage < ApplicationRecord
end

app/models/chat_room.rb
# frozen_string_literal: true

class ChatRoom < ApplicationRecord
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
end

app/models/password.rb
# frozen_string_literal: true

class Password < ApplicationRecord
  acts_as_paranoid
  has_secure_password

  belongs_to :user
end

app/models/refresh_token.rb
# frozen_string_literal: true

class RefreshToken < ApplicationRecord
  belongs_to :user
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  acts_as_paranoid

  has_many :refresh_tokens, dependent: :destroy
  has_one :password, dependent: :destroy
  has_one :user_secret, dependent: :destroy

  validates :email, uniqueness: true

  enum role: Constants::USER_ROLES

  def full_name
    f_name = first_name || ''
    l_name = last_name || ''
    "#{f_name} #{l_name}"
  end
end

app/models/user_online_status.rb
# frozen_string_literal: true

class UserOnlineStatus < ApplicationRecord
  belongs_to :user
end

app/models/user_secret.rb
# frozen_string_literal: true

class UserSecret < ApplicationRecord
  belongs_to :user
end

app/controllers/auth_controller.rb
# frozen_string_literal: true

class AuthController < ApplicationController
  def login; end

  def registration; end

  def forgot_password; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_path?(path = '')
    controller.controller_name == path.downcase
  end

  def full_title(page_title = '')
    base_title = 'RTemp'
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      "#{controller.controller_name.capitalize} | #{base_title}"
    end
  end

  def set_header?(state = false)
    !state
  end

  def log_in?
    @current_user.present?
  end

  def path_name(page_header_title = '')
    if page_header_title.present?
      page_header_title
    else
      controller.controller_name.capitalize
    end
  end

  def online_status_to_color(status)
    case status
    when 'online'
      'text-green'
    when 'offline'
      'text-red'
    else
      'text-gray'
    end
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/reports_helper.rb
# frozen_string_literal: true

module ReportsHelper
end

app/helpers/settings_helper.rb
# frozen_string_literal: true

module SettingsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag asset_path('logo.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= vite_client_tag %>
    <%= vite_stylesheet_tag 'application', data: { "turbo-track": "reload" } %>
    <%= vite_javascript_tag 'application' %>
    <%= action_cable_meta_tag %>
  </head>

  <body class="min-h-screen flex flex-col">
    <% if log_in? %>
      <%= render('shared/navbar') %>
      <main class="grow flex">
        <%= render('shared/sidebar') %>
        <div class="flex flex-col grow overflow-hidden overflow-hidden max-h-[calc(100vh-64px)] bg-background">
          <%= render('shared/page_header') %>
          <div class="p-[16px] grow">
            <%= yield %>
          </div>
        </div>
      </main>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/shared/_dropdown.html.erb
<div
  data-sidebar-dropdown-target="sidebarMenu"
  aria-orientation="vertical"
  aria-labelledby="menu-button"
  class="z-50 hidden absolute top-[40px] left-[100px] w-[160px] rounded-[3px] border-[1px] border-sidebar bg-white divide-[2px] divide-y divide-black focus:outline-none"
>
  <div class="py-1" role="none">
    <%= link_to 'My profile', me_users_path, role: "menuitem", tabindex: "-1",  id: "menu-item-0", class: 'block px-3 py-2 hover:bg-sidebar hover:text-white' %>
    <%= link_to 'Settings', settings_path, role: "menuitem", tabindex: "-1", id: "menu-item-1", class: 'block px-3 py-2 hover:bg-sidebar hover:text-white' %>
  </div>
  <div class="py-1">
    <%= link_to 'Logout', logout_path, data: { turbo_method: :post, }, role: "menuitem", tabindex: "-1", id: "menu-item-2", class: 'w-full block px-3 py-2 hover:bg-sidebar hover:text-white' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header class="bg-navbar py-2 px-[48px]">
  <div class="flex">
    <%= link_to(image_tag('logo.png', alt: 'logo', class: 'h-12'), root_path) %>
  </div>
</header>

app/views/shared/_page_header.html.erb
<div class="bg-white px-[16px] py-[24px] mb-[2px]">
  <p class="text-xl font-bold text-dark-blue"><%= path_name(yield(:page_header_title)) %></p>
</div>

app/views/shared/_sidebar.html.erb
<nav data-controller="sidebar-dropdown" class="flex flex-col w-[200px] bg-sidebar select-none">
  <div data-action="click->sidebar-dropdown#toggleSidebarMenu" data-type="menu" data-sidebar-dropdown-target="sidebarProfile" class="mt-[8px] px-[16px] py-[12px] flex cursor-pointer hover:bg-bluegray relative">
    <%= image_tag('avatar-thumbnail.png', class: 'h-[32px] w-[32px] pointer-events-none') %>
    <%= content_tag(:p, @current_user.full_name, class: 'h-fit my-auto ml-[8px] text-white grow pointer-events-none') %>
    <%= image_tag("menu-arrow.svg", class: "w-[12px] pointer-events-none") %>
    <%= render 'shared/dropdown' %>
  </div>
  <div class="flex flex-col my-[8px]">
    <% [{ name: 'Dashboard', path: root_path, icon: 'dashboard' },
        { name: 'Tasks', path: tasks_path, icon: 'tasks' },
        { name: 'Messages', path: messages_path, icon: 'messages' },
        { name: 'Groups', path: groups_path, icon: 'groups' }].each do |link| %>
      <%= link_to(
        link[:path], src: link[:path],
        class: 'flex align-middle h-[48px] my-auto text-white cursor-pointer hover:bg-bluegray'
      ) do %>
        <% if current_path?(link[:name]) %>
          <%= content_tag(:div, '', class: 'w-[3px] bg-orange') %>
        <% end %>
        <%= image_tag("menu-#{link[:icon]}.svg", class: "w-[20px] #{current_path?(link[:name]) ? 'filter-orange ml-[16px]' : 'filter-white ml-[19px]'}") %>
        <%= content_tag(:p, link[:name], class: "h-fit my-auto text-[16px] ml-[8px] #{'text-orange' if current_path?(link[:name])}")%>
      <% end %>
    <% end %>
  </div>
  <%= content_tag(:div, '', class: 'h-[2px] w-full bg-lightgray') %>
  <div class="flex flex-col my-[8px]">
    <% [{ name: 'Users', path: users_path },
        { name: 'Reports', path: reports_path }].each do |link| %>
      <%= link_to(
        link[:path], src: link[:path],
        class: 'flex align-middle h-[32px] my-auto text-white cursor-pointer hover:bg-bluegray'
      ) do %>
        <% if current_path?(link[:name]) %>
          <%= content_tag(:div, '', class: 'w-[3px] bg-orange') %>
        <% end %>
        <%= content_tag(:p, link[:name], class: "h-fit my-auto text-[16px] #{current_path?(link[:name]) ? 'text-orange ml-[16px]' : 'ml-[19px]'}")%>
      <% end %>
    <% end %>
  </div>
  <div class="px-[8px] mt-[48px]">
    <%= content_tag(:p, '© Ivan Vasiliev, 2022', class: 'text-[12px] text-white opacity-40') %>
  </div>
</nav>